# Generated by Django 4.2.16 on 2024-09-22 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_remove_adanswer_user_alter_adquestion_correct_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adquestion',
            name='correct_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correct_answer', to='ads.adanswer'),
        ),
    ]
