# Generated by Django 4.2.16 on 2024-09-22 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_alter_adquestion_correct_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradhistory',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
