# Generated by Django 5.1.1 on 2024-09-24 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_useradhistory_is_correct'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('ad_type', models.CharField(choices=[('survey', 'Surveys'), ('video', 'Videos'), ('post', 'Posts')], max_length=10)),
                ('category', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='PostAd',
            fields=[
                ('basead_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ads.basead')),
                ('post_text', models.TextField()),
                ('photo', models.ImageField(upload_to='ads/photos/')),
            ],
            bases=('ads.basead',),
        ),
        migrations.CreateModel(
            name='SurveyAd',
            fields=[
                ('basead_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ads.basead')),
                ('photo', models.ImageField(upload_to='ads/photos/')),
            ],
            bases=('ads.basead',),
        ),
        migrations.CreateModel(
            name='VideoAd',
            fields=[
                ('basead_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ads.basead')),
                ('video', models.FileField(upload_to='ads/videos/')),
            ],
            bases=('ads.basead',),
        ),
        migrations.CreateModel(
            name='AdImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ads/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ads.basead')),
            ],
        ),
        migrations.AlterField(
            model_name='adquestion',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='ads.basead'),
        ),
        migrations.AlterField(
            model_name='useradhistory',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.basead'),
        ),
        migrations.DeleteModel(
            name='Ad',
        ),
    ]
