# Generated by Django 5.1.1 on 2024-09-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_basead_postad_surveyad_videoad_adimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basead',
            name='boost_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basead',
            name='is_boosted',
            field=models.BooleanField(default=False),
        ),
    ]
