# Generated by Django 5.1.1 on 2024-09-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_basead_boost_end_date_basead_is_boosted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postad',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='ads/photos/'),
        ),
        migrations.AlterField(
            model_name='postad',
            name='post_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='surveyad',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='ads/photos/'),
        ),
        migrations.AlterField(
            model_name='videoad',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='ads/videos/'),
        ),
    ]
